CREATE OR REPLACE PACKAGE om_helper_pkg_test IS


    --%suite(om_helper_pkg_test)
    --%suitepath(alltests)
    
END om_helper_pkg_test;
/
CREATE OR REPLACE PACKAGE BODY om_helper_pkg_test IS

    /* generated by utPLSQL for SQL Developer on 2019-05-26 17:27:16 */

END om_helper_pkg_test;
/
